/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CopService } from "../cop.service";
import { CopCreateInput } from "./CopCreateInput";
import { Cop } from "./Cop";
import { CopFindManyArgs } from "./CopFindManyArgs";
import { CopWhereUniqueInput } from "./CopWhereUniqueInput";
import { CopUpdateInput } from "./CopUpdateInput";
import { DistressSignalFindManyArgs } from "../../distressSignal/base/DistressSignalFindManyArgs";
import { DistressSignal } from "../../distressSignal/base/DistressSignal";
import { DistressSignalWhereUniqueInput } from "../../distressSignal/base/DistressSignalWhereUniqueInput";
import { RatingFindManyArgs } from "../../rating/base/RatingFindManyArgs";
import { Rating } from "../../rating/base/Rating";
import { RatingWhereUniqueInput } from "../../rating/base/RatingWhereUniqueInput";

export class CopControllerBase {
  constructor(protected readonly service: CopService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cop })
  async createCop(@common.Body() data: CopCreateInput): Promise<Cop> {
    return await this.service.createCop({
      data: data,
      select: {
        createdAt: true,
        displayName: true,
        earnedRatings: true,
        email: true,
        id: true,
        location: true,
        phone: true,
        totalRatings: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Cop] })
  @ApiNestedQuery(CopFindManyArgs)
  async cops(@common.Req() request: Request): Promise<Cop[]> {
    const args = plainToClass(CopFindManyArgs, request.query);
    return this.service.cops({
      ...args,
      select: {
        createdAt: true,
        displayName: true,
        earnedRatings: true,
        email: true,
        id: true,
        location: true,
        phone: true,
        totalRatings: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cop(@common.Param() params: CopWhereUniqueInput): Promise<Cop | null> {
    const result = await this.service.cop({
      where: params,
      select: {
        createdAt: true,
        displayName: true,
        earnedRatings: true,
        email: true,
        id: true,
        location: true,
        phone: true,
        totalRatings: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCop(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() data: CopUpdateInput
  ): Promise<Cop | null> {
    try {
      return await this.service.updateCop({
        where: params,
        data: data,
        select: {
          createdAt: true,
          displayName: true,
          earnedRatings: true,
          email: true,
          id: true,
          location: true,
          phone: true,
          totalRatings: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCop(
    @common.Param() params: CopWhereUniqueInput
  ): Promise<Cop | null> {
    try {
      return await this.service.deleteCop({
        where: params,
        select: {
          createdAt: true,
          displayName: true,
          earnedRatings: true,
          email: true,
          id: true,
          location: true,
          phone: true,
          totalRatings: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/distressSignals")
  @ApiNestedQuery(DistressSignalFindManyArgs)
  async findDistressSignals(
    @common.Req() request: Request,
    @common.Param() params: CopWhereUniqueInput
  ): Promise<DistressSignal[]> {
    const query = plainToClass(DistressSignalFindManyArgs, request.query);
    const results = await this.service.findDistressSignals(params.id, {
      ...query,
      select: {
        civilian: {
          select: {
            id: true,
          },
        },

        cop: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        location: true,
        message: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/distressSignals")
  async connectDistressSignals(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() body: DistressSignalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      distressSignals: {
        connect: body,
      },
    };
    await this.service.updateCop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/distressSignals")
  async updateDistressSignals(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() body: DistressSignalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      distressSignals: {
        set: body,
      },
    };
    await this.service.updateCop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/distressSignals")
  async disconnectDistressSignals(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() body: DistressSignalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      distressSignals: {
        disconnect: body,
      },
    };
    await this.service.updateCop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/ratings")
  @ApiNestedQuery(RatingFindManyArgs)
  async findRatings(
    @common.Req() request: Request,
    @common.Param() params: CopWhereUniqueInput
  ): Promise<Rating[]> {
    const query = plainToClass(RatingFindManyArgs, request.query);
    const results = await this.service.findRatings(params.id, {
      ...query,
      select: {
        civilian: {
          select: {
            id: true,
          },
        },

        comment: true,

        cop: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        ratingValue: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ratings")
  async connectRatings(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() body: RatingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ratings: {
        connect: body,
      },
    };
    await this.service.updateCop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ratings")
  async updateRatings(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() body: RatingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ratings: {
        set: body,
      },
    };
    await this.service.updateCop({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ratings")
  async disconnectRatings(
    @common.Param() params: CopWhereUniqueInput,
    @common.Body() body: RatingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ratings: {
        disconnect: body,
      },
    };
    await this.service.updateCop({
      where: params,
      data,
      select: { id: true },
    });
  }
}
