/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsInt } from "class-validator";
import { DistressSignalCreateNestedManyWithoutCopsInput } from "./DistressSignalCreateNestedManyWithoutCopsInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { RatingCreateNestedManyWithoutCopsInput } from "./RatingCreateNestedManyWithoutCopsInput";

@InputType()
class CopCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  displayName?: string | null;

  @ApiProperty({
    required: false,
    type: () => DistressSignalCreateNestedManyWithoutCopsInput,
  })
  @ValidateNested()
  @Type(() => DistressSignalCreateNestedManyWithoutCopsInput)
  @IsOptional()
  @Field(() => DistressSignalCreateNestedManyWithoutCopsInput, {
    nullable: true,
  })
  distressSignals?: DistressSignalCreateNestedManyWithoutCopsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  earnedRatings?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  location?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => RatingCreateNestedManyWithoutCopsInput,
  })
  @ValidateNested()
  @Type(() => RatingCreateNestedManyWithoutCopsInput)
  @IsOptional()
  @Field(() => RatingCreateNestedManyWithoutCopsInput, {
    nullable: true,
  })
  ratings?: RatingCreateNestedManyWithoutCopsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalRatings?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userId?: string | null;
}

export { CopCreateInput as CopCreateInput };
